### ISSUE TITLE
Nuova versione quando?

### ISSUE THREAD

**Issue by mariantanase** [WPGov/wp-attachments#4]
Quali sono le differenze tra la vecchia versione 5.0.6 e la più recente ?

**Comment by milesimarco** [comment]
Ciao @mariantanase,
ho rilasciato una nuova versione direttamente qui su Github. Purtroppo per un problema di versioning non è ancora visibile su wordpress.org (già la versione 5.0.6 conteneva il bugfixing ma era stata erroneamente inclusa).
Segnalo a titolo informativo che la vulnerabilità è sfruttabile solo da attackers con privilegi amministrativi di WordPress.

M.
